### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AmbiMod** [waldobronchart/AmbientLightServer#1]
I Waldo,

It's not an Issue, not yet, but this is the only way i found to contact you.

I have a blog on Ambilight, that you can take a look here https://ambimod.jimdo.com, where i recently write an article talking about the 3 most awesome Ambilight Solution that we can purchase.

When i start searching information about Ambivision Pro, i found your website where you shared your project about an Ambilight Solution using a Raspberry, USB camera and the most important thing, your own application.

I reproduce the same with my Raspberry Pi Zero, a FishEye Picamera and Hyperion for the software part. 
With this last, is very hard to keep the detection zone in a good position. The camera is too far, or i have a problem with the angle, the vertical/horizontal detection strip are not in a good place on the captured image...

So i write a tutorial to use it in Hue Like mode, because the detection zone are more bigger ( half of the screen for example )  than the Ambilight Mode. ( screen border ).

Not happy to see the result, i decide to try seeing if i can use your application. I installed Raspbian Jessie in Full version, all the dependencies, and launched the OpenCV compilation ( a long day for me because it take more than 12 hours to do ).
The last thing i need to do : 
- Get your application Server and Client on my Raspberry

I understood the most part to make it working but i have a  question : 
- I use to play with PWM or SPI LED strip connected directly on a Pi or a NodeMCU. I don't use WiringPi before so, i asked myself how i can define my Ambilight Installation in a file like the number of led on each side, the type and model that i use, the  position of the 1st led ... and wich one i need to edit to put this informations ??

And one maybe more personal :
- Why did you stop the development of your awesome Application ? You was in advance on your time doing Ambilight like you did. Bad luck, if you proposed to do the same in an easiest way, i think, today, it would have been the most used Ambilight application.

Hope i don't come 4 years later and really want to thank you in advance for your answers and your work. 

Regards.
YouS

PS : I saw that you live in Canada and work to UbiSoft. Maybe you can Answer to me in French if you can and i you want to. I lived 6 months in Montréal, Good city ;-) but too cold for me.

**Comment by waldobronchart** [comment]
Hi. Apologies for the late reply.

The settings you are looking for are all defined in the file `HardwareConfig.h`. There you can change the pins, number of leds, etc.. I put this code up just as an example implementation, and since it is used to control my custom built hardware, people who want to use it will need to make some changes. It isn't plug and play.

It was always just a personal project, I wasn't interested in creating a product.

**Comment by waggy685** [comment]
Hello Waldo !

Thanks for your good work ! 
**How do I run the AmbientLightServer with the Onboard 5MP Camera ?** 
 /dev/video* says that there is a video0, but it does not use the libwebcam

> [libwebcam] Invalid V4L2 control type encountered: ctrl_id = 0x00980001, name =                                              'User Controls', type = 6
> [libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0098000                                             1, name = 'User Controls'
> [libwebcam] Unknown V4L2 user control ID encountered: 0x0098090E (V4L2_CID_USER_                                             BASE + 14)
> [libwebcam] Unknown V4L2 user control ID encountered: 0x0098090F (V4L2_CID_USER_                                             BASE + 15)
> [libwebcam] Unknown V4L2 user control ID encountered: 0x00980914 (V4L2_CID_USER_                                             BASE + 20)
> [libwebcam] Unknown V4L2 user control ID encountered: 0x00980915 (V4L2_CID_USER_  

greetings from Austria. 
Stephan

**Comment by waldobronchart** [comment]
Hi Stepan, I'm not sure. Capturing that might be supported by OpenCV, or if not you'll need swap out the OpenCV library for the picamera library. Quick google search led me to this: https://www.uco.es/investiga/grupos/ava/node/40

**Comment by waggy685** [comment]
HI Waldo ! 
I found some Webcam, which is dedected as /dev/video0 but:

**> [libwebcam] Invalid V4L2 control type encountered: ctrl_id = 0x00980001, name =                                  'User Controls', type = 6
> [libwebcam] Invalid or unsupported V4L2 control encountered: ctrl_id = 0x0098000                                 1, name = 'User Controls'
> [libwebcam] Unknown V4L2 user control ID encountered: 0x00980914 (V4L2_CID_USER_                                 BASE + 20)
> [libwebcam] Unknown V4L2 user control ID encountered: 0x00980915 (V4L2_CID_USER_                                 BASE + 21)
> ERROR: Unknown control specified.**
> [2017-11-23 09:21:52.193] [INFO]        Loading Preferences from file:
> [2017-11-23 09:21:52.195] [DEBUG]        - boundsTopLeft = (0.196875,0.239583)
> [2017-11-23 09:21:52.195] [DEBUG]        - boundsTopRight = (0.8625,0.227083)
> [2017-11-23 09:21:52.196] [DEBUG]        - boundsBottomRight = (0.8,0.8)
> [2017-11-23 09:21:52.196] [DEBUG]        - boundsBottomLeft = (0.2,0.8)
> [2017-11-23 09:21:52.196] [DEBUG]        - totalFadeTimeMS = 200
> [2017-11-23 09:21:52.196] [DEBUG]        - fixedColorEnabled = false
> [2017-11-23 09:21:52.197] [DEBUG]        - fixedColor = (0,0,0)
> [2017-11-23 09:21:52.197] [DEBUG]        - camBrightness = 61
> [2017-11-23 09:21:52.197] [DEBUG]        - camContrast = 89
> [2017-11-23 09:21:52.197] [DEBUG]        - camSaturation = 142
> [2017-11-23 09:21:52.198] [DEBUG]        - camGain = 183
> [2017-11-23 09:21:52.198] [INFO]        Saving Preferences
> [2017-11-23 09:21:52.199] [INFO]        LEDController: setting up with ClockPin1                                 =0 DataPin1=1 ClockPin2=3 DataPin2=4
**> HIGHGUI ERROR: V4L/V4L2: VIDIOC_CROPCAP
> HIGHGUI ERROR: V4L: setting property #5 is not supported
> HIGHGUI ERROR: V4L/V4L2: VIDIOC_CROPCAP**

The Client connects successfully, but sends an Error once I change to the "Sampler"-window. 

does that mean, that my Creative Webcam VF330 is not supported ? 
thanks in advance, Stephan !

**Comment by waldobronchart** [comment]
Check first if your webcam is working in other applications. That way you can narrow down whether the issue is with this application or with your webcam setup.

**Comment by waggy685** [comment]
Hi Waldo !

It works, but I still get this error message:

```
HIGHGUI ERROR: V4L/V4L2: VIDIOC_CROPCAP
HIGHGUI ERROR: V4L: setting property #5 is not supported
HIGHGUI ERROR: V4L/V4L2: VIDIOC_CROPCAP
```
The Clients shows the preview picture, but also an error message:

Exception in threat: Value Error. 

Today i will try to connect the LEDS. 

chears. Stephan

**Comment by waldobronchart** [comment]
Hi. I recommend searching the net for `HIGHGUI ERROR: V4L/V4L2: VIDIOC_CROPCAP` and seeing how other people solved it.

Regarding the client error, see if you can get a callstack. That doesn't tell me much

**Comment by jimmyeao** [comment]
The OpenCV support for V4L2 controls for the Pi Camera is limited, I spent days trying to get the Pi Camera to play nicely, and in the end, gave in and used a USB camera (Logitech C270) which worked the first time. This also has the benefit of being able to use a USB extension cable to locate the camera wherever I need.
