### ISSUE TITLE
Does it support fisheye cameras?

### ISSUE THREAD

**Issue by FuurioBR** [waldobronchart/AmbientLightServer#11]
I mean, does the software have a thing for distorting the image into something usable like Govee Immersion TV Light Kit has?

**Comment by waldobronchart** [comment]
No, the sampling code I used is linear between 4 points. A fisheye lens will curve the frame of the display so you will need to tweak the sampling code to use something like bezier, for example:

![bezier](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Bezier_curve.svg/1200px-Bezier_curve.svg.png)

where `P0` and `P1` are two corners of the tv frame.
