### ISSUE TITLE
Supported Cams

### ISSUE THREAD

**Issue by giovanne123** [waldobronchart/AmbientLightServer#3]
Are there special requirements for a cam which will be supported?
Do the cam have to support the v4l2 driver? Or will the cam be ok if it is connected as /dev/video0 

I think picam would be fine, because maybe faster than usbcam :-)

**Comment by waldobronchart** [comment]
Probably depends on the pi version, linux distribution and opencv version you are using. The main thing that you want is to be able to set the exposure setting to a fixed value so it doesn't jump around while the tv image changes.

**Comment by giovanne123** [comment]
Thanks for the answer.
Currently I only have an cheap usbcam (hama snakecam), maybe it isn't ideal. Used it only for testing because I haven't a different at the moment...
For the next test and to have this comparable I will wait for the logitech c250 which will come in the next days. After that I will also test the picam, but it has to arrive from china ;-)

I will let you know the results.
In the meantime I try to understand 'exposure' and your source code ;-)

**Comment by waldobronchart** [comment]
Try capturing a frame from the webcam using a command line; if that works then the opencv capture should work too

**Comment by giovanne123** [comment]
opencv captures right, maybe my LEDs aren't connected correctly to the Pi GPIOs...?
I wait for the Logitech C250 and Picam an will see how it works and will setup a little test environment to not modify my hyperion installation - maybe I will need it also...

**Comment by jimmyeao** [comment]
@giovanne123 let me know how you get on with the PiCam, I'm currently struggling with it - would be good if there was a debug flag we could turn out to say if it managed to capture an image, I'll have a dig through the sourcecode tonight and see if I can figure this out.

**Comment by diabolo86** [comment]
@giovanne123 Did you get the PiCam running?

**Comment by gbkwiatt** [comment]
I would like to use pi camera too. not sure where to start with that
