### ISSUE TITLE
wrong color?

### ISSUE THREAD

**Issue by azak1r** [waldobronchart/AmbientLightServer#6]
hey waldo not sure if you are still watching for issues or questions here but thought it woud be worth a try.

I managed to get your little ambientlightserver running and it looks amazing. The only thing im running into right now is that whenever a dark scene is playing or some parts of the screen got black the leds don't do what you would think they would do. 

The go green instead of going off. Any idea what could be wrong?

**Comment by yuryminsk** [comment]
HI Waldo, I have to admit that I also have mentioned issue with a green lights for black screen.
It would be very nice if you can share your ideas on this.

**Comment by azak1r** [comment]
I abandoned this and went to hyperion ng and that works out of the box
