### ISSUE TITLE
LED Flashes occasionally ( ws2812B )

### ISSUE THREAD

**Issue by gbkwiatt** [waldobronchart/AmbientLightServer#8]
What a great program, and client too. After 8 years I am still very interested in that. 

Just made it work with ws2812B  and https://github.com/jgarff/rpi_ws281x driver.

One thing I noticed, sometimes all of the sudden all LED flashes for no reason, not sure if that's related to hardware, or it actually gets spikes like that from camera ? 

Also is there any graceful shutdown ? so it switches LED off on exit or gpio pi? 

I am planning to make it work only when GPIO pin is high, so that when tv is on only.

**Comment by waldobronchart** [comment]
I'm not actively maintaining this, but I think you can do something like I did here:

https://github.com/waldobronchart/window-farm-client-rpi/blob/master/src/main.cpp#L73-L80
https://github.com/waldobronchart/window-farm-client-rpi/blob/master/src/main.cpp#L49-L55

That will give you a callback before the app exits, which you can use to set all lights to a fixed color.

**Comment by gbkwiatt** [comment]
I actually started writing my own thing in NodeJs,  and thing that works with ws218x LEDs. 
But this repository is a nice inspiration for ideas and how to solve some colors things. 

The issue I had with flashing LEds wat actually me being stupid and powering over 100 LEDs with 2A power supply. 
Also noise was coming from GPIO which I eventually "burned" as I didn't use any level shifter. 

With level shifter and good PSU it worked very well for 220 LEDs.

**Comment by waldobronchart** [comment]
Ok nice! Glad this code helped you out
