### ISSUE TITLE
Turn off bottom row feature

### ISSUE THREAD

**Issue by gbkwiatt** [waldobronchart/AmbientLightServer#9]
How hard would be to add option to exclude bottom row from getting colors ? 

I am having 1 strand change, or maybe just
```cpp
for (int i=0; i<TOTAL_NUM_LEDS - NUM_LEDS_HORIZONTAL ; ++i)
	{
		Color color = lerpColor(m_prevColorBuffer[i], colorBuffer[i], lerpTerm);

		ShiftOut8Bits(GPIO_CLOCK_PIN1, GPIO_DATA_PIN1, color.ByteR());
		ShiftOut8Bits(GPIO_CLOCK_PIN1, GPIO_DATA_PIN1, color.ByteG());
		ShiftOut8Bits(GPIO_CLOCK_PIN1, GPIO_DATA_PIN1, color.ByteB());

		m_prevColorBuffer[i] = color;
	}
```

If I am correct ? or 
```cpp
for (int i=0; i<TOTAL_NUM_LEDS  ; ++i)
	{
		Color color = lerpColor(m_prevColorBuffer[i], colorBuffer[i], lerpTerm);
          if(i<= TOTAL_NUM_LEDS - NUM_LEDS_HORIZONTAL)
             {
		ShiftOut8Bits(GPIO_CLOCK_PIN1, GPIO_DATA_PIN1, color.ByteR());
		ShiftOut8Bits(GPIO_CLOCK_PIN1, GPIO_DATA_PIN1, color.ByteG());
		ShiftOut8Bits(GPIO_CLOCK_PIN1, GPIO_DATA_PIN1, color.ByteB());
             }
		m_prevColorBuffer[i] = color;
	}
```

**Comment by waldobronchart** [comment]
You could just set the color buffer for those indices to the color that you want them to be.

something like `colorBuffer[12] = Color(...);`

**Comment by gbkwiatt** [comment]
Sorry to bother you, you might probably don't remember, I am trying to figure out, what areas you check for colors in the Trapezoid Sampler. 

I have my own idea, I am actually reshaping my trapeze to rectangle, and then I divide edges to smaller rects and will get dominant color of each rect. At least that's the idea. 

Because I am not very proficient with Cpp, I am trying to read your code and figure out your approach.
It also looks like you are only using OpenCv to capture image and return in rare data ? 
I am really struggling to figure that out from your code ;)

**Comment by waldobronchart** [comment]
@gbkwiatt the easiest thing to do (if I'm understanding correctly) is to use the client (https://github.com/waldobronchart/AmbientLightPyClient) to setup the sampling area.

If you want a perfect rectangle, then you can just drag the corners into the frame corners:
![image](https://user-images.githubusercontent.com/464795/103371075-8dd78f00-4a9c-11eb-8b78-e50f715f864a.png)

If you want to do it purely through code, then you can just manually configure it like this:
1. Set the number of LEDs, rows, columns here: https://github.com/waldobronchart/AmbientLightServer/blob/master/HardwareConfig.h#L8-L11
2. Set the bounds coordinates (4 points) directly: 
  https://github.com/waldobronchart/AmbientLightServer/blob/master/Preferences.h#L33-L36
  Something like this should work:
  ```
  Preferences::Instance->BoundsTopLeft = Vector2(0, 0);
  ...
  ```
